# Generated by Django 4.0.4 on 2022-05-16 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completed',
            new_name='complete',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='tile',
            new_name='title',
        ),
    ]
